package ar.edu.unlam.tp2;

public enum Localidad {
	
	SAN_JUSTO, RAMOS_MEJIA, ISIDRO_CASANOVA, LAFERRERE, GONZALEZ_CATAN, LA_TABLADA, LOMAS_DEL_MIRADOR,
	VILLA_LUZURIAGA, VILLA_MADERO, RAFAEL_CASTILLO, OTRAS

}
