package ar.edu.unlam.tp2;

public enum OpcionesDeMenu {
	
	INGRESAR_PACIENTE, BUSCAR_PACIENTE_POR_DNI, LISTAR_PACIENTES_INGRESADOS, DAR_ALTA_PACIENTE, CONSULTAR_REGISTRO_DE_PACIENTES_DADOS_DE_ALTA,
	TOTAL_DE_PACIENTES_INGRESADOS, CONSULTAR_CAMAS_DISPONIBLES, SALIR, INGRESE_UNA_OPCION_VALIDA

}
